name: mortar-deploy-action
description: Github action for deploy a mortar project
author: 'robur <ho.doh@bucketplace.net>'
inputs:
  aws-access-key-id:
    description: "AWS Access Key Id for ECR"
    required: true
  aws-secret-access-key:
    description: "AWS Secret Access Key for ECR"
    required: true
  aws-region:
    description: "AWS Region for ECR"
    required: true
  nexus-url:
    description: "Nexus URL where all the packages are published"
    required: true
    default: "nexus-repository-manager.nexus:8081"
  nexus-user:
    description: "Nexus User ID:PW that has permission to publish packages to maven and npm repositories"
    required: true
  prod:
    description: "is production or not"
    required: true
    default: "false"
  path:
    description: "path of mortar project"
    required: false
    default: "."
  dry-run:
    description: "dry run"
    required: false
    default: "false"
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Mortar Deployment 
      run: mortar deploy -y --nexus-user=${{ inputs.nexus-user }} --nexus-url=${{ inputs.nexus-url }} --prod=${{ inputs.prod }} --config=${{ inputs.path }}/mortar.yaml --ecr-repository-region=${{ inputs.aws-region }} --ecr-repository-url=${{ steps.login-ecr.outputs.registry }} --dry-run=${{ inputs.dry-run }}
      shell: bash