---
name: "Release Mortar Deploy Action"

on:
  release:
    types:
      - "released"

jobs:
  update_major_tag:
    name: "Update Major Tags"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get the version
        id: get-version
        run: echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Parse semver string
        id: semver-parser
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ steps.get-version.outputs.version }}
      - name: push Major Tag
        id: tag-major-version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: v${{ steps.semver-parser.outputs.major }}
      - name: push Latest Tag
        id: tag-latest-version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: latest
