---
name: "Release Mortar Deploy Action"

on:
  release:
    types:
      - "released"

jobs:
  update_major_tag:
    name: "Update Major Tags"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get the version
        id: get-version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      - name: Parse semver string
        id: semver-parser
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ steps.get-version.outputs.version }}
      - name: Delete Major.Minor Tag
        continue-on-error: true
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: "v${{ steps.semver-parser.outputs.major }}.${{ steps.semver-parser.outputs.minor }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_release: false
      - name: push Major.Minor Tag
        uses: mathieudutour/github-tag-action@v6.0
        with:
          fetch_all_tags: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: "${{ steps.semver-parser.outputs.major }}.${{ steps.semver-parser.outputs.minor }}"
      - name: delete Major Tag
        continue-on-error: true
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: "v${{ steps.semver-parser.outputs.major }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_release: false
      - name: push Major Tag
        id: tag-major-version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          fetch_all_tags: true
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.semver-parser.outputs.major }}
      - name: delete Latest Tag
        continue-on-error: true
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: latest
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_release: false
      - name: push Latest Tag
        id: tag-latest-version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: latest
          tag_prefix: ""
