
name: 'action-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:

jobs:
  build:
    runs-on: [self-hosted, Linux, X64, mortar-runner]
    steps:
    - uses: actions/checkout@v2
      with:
        repository: bucketplace/mortar-cli
        path: example/mortar
    - name: testing
      uses: ./
      with:
        dry-run: "true"
        
        
